#!/bin/bash

help() {
    echo "install, installing audiocast on server/receiver."
    echo
    echo "Basic usage:"
    echo "install [option]"
    echo
    echo "Options:"
    echo "  server      installation for server (rtp-send)"
    echo "  receiver    installation for receiver (rtp-recv)"
}

[[ $# -eq 0 || $# -gt 1 ]] && help && exit

valid=(server receiver)
(printf '%s\n' "${valid[@]}" | grep -xq $1) || { help && exit; }

sudo cp $1/audiocast /usr/bin

if [[ $1 == 'server' ]]; then
    cache_dir=${XDG_CACHE_HOME:-$HOME/.cache}/audiocast
    mkdir -p $cache_dir

    conf_dir=${XDG_CONFIG_HOME:-$HOME/.config}
    default_pulse_conf=$conf_dir/pulse/default.pa
    [[ ! -f $default_pulse_conf ]] && default_pulse_conf=/etc/pulse/default.pa

    pulse_conf="load-module module-null-sink sink_name=rtp format=s16le rate=48000 channels=2 sink_properties=\"device.description='RTP Multicast Sink'\""
    [[ -z $(cat $default_pulse_conf | grep "^$pulse_conf") ]] && { \
        [[ $default_pulse_conf == /etc/pulse/default.pa ]] && \
            sudo echo $pulse_conf >> $default_pulse_conf || \
            echo $pulse_conf >> $default_pulse_conf; }

    systemctl --user restart pulseaudio

elif [[ $1 == 'receiver' ]]; then
    sudo cp receiver/audiocast.service /etc/systemd/user
    systemctl --user daemon-reload
fi

